"""Generate a minimal SPDX 2.3 SBOM for uibc-core (standard library only).

The package has no runtime dependencies, so the SBOM is intentionally small:
one package, its Python source files with SHA-256 checksums, and CONTAINS
relationships. Kept in-repo so the SBOM can be regenerated by anyone.

SPDX compliance notes (fixes applied after independent expert review,
2026-09-18):
  * element identifiers only use characters allowed by the SPDX 2.3 ID
    grammar ([A-Za-z0-9.-]); path separators and underscores are normalised
    to '-' so that e.g. ``uibc_core/__init__.py`` becomes
    ``SPDXRef-File-uibc-core--init.py``.
  * ``hasExtractedLicensingInfos`` is not emitted: Apache-2.0 is on the SPDX
    licence list, so an extracted-licence block with ``licenseId`` =
    ``Apache-2.0`` would violate SPDX 2.3 section 10.1 (that section is only
    for licences *not* on the list, and requires a ``LicenseRef-`` id).
  * ``licenseListVersion`` tracks the current SPDX licence list.
"""

import datetime
import hashlib
import json
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSION = "0.2.1"
SPDX_LICENSE_LIST_VERSION = "3.29.0"


def git(*args):
    return subprocess.run(
        ["git", "-C", ROOT, *args], capture_output=True, text=True
    ).stdout.strip()


def sha256(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def spdx_id(path):
    """Map a repo-relative path to a valid SPDX element identifier."""
    return "SPDXRef-File-" + re.sub(r"[^A-Za-z0-9.]+", "-", path)


def collect():
    out = []
    for dirpath, _dirnames, filenames in os.walk(os.path.join(ROOT, "uibc_core")):
        for name in filenames:
            if name.endswith(".py"):
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, ROOT).replace("\\", "/")
                out.append({"rel": rel, "sha256": sha256(full)})
    return sorted(out, key=lambda item: item["rel"])


def build(files):
    head = git("rev-parse", "HEAD")
    doc = {
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": f"uibc-core-{VERSION}",
        "documentNamespace": (
            "https://github.com/zhaoxinghua09-cell/uibc-core/spdx/"
            f"{VERSION}-{head[:12]}"
        ),
        "creationInfo": {
            "created": datetime.datetime.now(datetime.timezone.utc).strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
            "creators": [
                "Person: Xinghua Zhao (Steven Zhao)",
                "Tool: gen-sbom.py (Python standard library)",
            ],
            "licenseListVersion": SPDX_LICENSE_LIST_VERSION,
            "comment": (
                "Minimal SBOM. uibc-core has no runtime dependencies beyond the "
                "Python standard library, so there is no dependency graph to "
                "express beyond the package's own files."
            ),
        },
        "packages": [
            {
                "name": "uibc-core",
                "SPDXID": "SPDXRef-Package-uibc-core",
                "versionInfo": VERSION,
                "downloadLocation": "https://github.com/zhaoxinghua09-cell/uibc-core",
                "filesAnalyzed": True,
                "licenseConcluded": "Apache-2.0",
                "licenseDeclared": "Apache-2.0",
                "copyrightText": "Copyright 2026 Xinghua Zhao (Steven Zhao)",
                "supplier": "Person: Xinghua Zhao (Steven Zhao)",
                "externalRefs": [
                    {
                        "referenceCategory": "PACKAGE-MANAGER",
                        "referenceType": "purl",
                        "referenceLocator": f"pkg:pypi/uibc-core@{VERSION}",
                    }
                ],
            }
        ],
        "relationships": [
            {
                "spdxElementId": "SPDXRef-DOCUMENT",
                "relatedSpdxElement": "SPDXRef-Package-uibc-core",
                "relationshipType": "DESCRIBES",
            }
        ],
        "files": [
            {
                "fileName": item["rel"],
                "SPDXID": spdx_id(item["rel"]),
                "checksums": [
                    {"algorithm": "SHA256", "checksumValue": item["sha256"]}
                ],
                "licenseConcluded": "Apache-2.0",
                "copyrightText": "Copyright 2026 Xinghua Zhao (Steven Zhao)",
            }
            for item in files
        ],
    }
    for item in doc["files"]:
        doc["relationships"].append(
            {
                "spdxElementId": "SPDXRef-Package-uibc-core",
                "relatedSpdxElement": item["SPDXID"],
                "relationshipType": "CONTAINS",
            }
        )
    return doc


def main():
    files = collect()
    doc = build(files)
    ids = [f["SPDXID"] for f in doc["files"]]
    assert len(ids) == len(set(ids)), "duplicate SPDX element identifiers"
    for one in ids:
        assert re.fullmatch(r"[A-Za-z0-9.-]+", one[len("SPDXRef-"):]), one
    out = os.path.join(ROOT, "sbom.spdx.json")
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    print(f"wrote {out}")
    print(f"files: {len(files)}")
    print(f"HEAD: {git('rev-parse', 'HEAD')[:12]}")


if __name__ == "__main__":
    main()
